steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_IMAGE_NAME}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
      - --build-arg
      - NEXT_PUBLIC_GOOGLE_AUTH_ENABLED=${_NEXT_PUBLIC_GOOGLE_AUTH_ENABLED}
      - --build-arg
      - NEXT_PUBLIC_MFA_ENABLED=${_NEXT_PUBLIC_MFA_ENABLED}
      - --build-arg
      - NEXT_PUBLIC_ADMIN_COMMAND_GRID_V2=${_NEXT_PUBLIC_ADMIN_COMMAND_GRID_V2}
      - --build-arg
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - .
images:
  - ${_IMAGE_NAME}
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
