export type SuiteToolLayoutVariant = 'standard' | 'workbench' | 'editor' | 'agent';
export type SuiteToolMobilePriority = 'quick' | 'standard' | 'advanced' | 'desktopEnhanced';
export type SuiteToolMobileEntry = 'route' | 'sheet' | 'focused';

export interface SuiteToolDefinition {
  id: string;
  path: string;
  title: string;
  subtitle: string;
  eyebrow: string;
  icon: string;
  group: string;
  layoutVariant: SuiteToolLayoutVariant;
  pageHelpId?: string;
  mobilePriority?: SuiteToolMobilePriority;
  mobileEntry?: SuiteToolMobileEntry;
  mobileHref?: string;
  mobileLabel?: string;
  mobileDescription?: string;
  mobileActionLabel?: string;
}

export const suiteToolRegistry = [
  {
    id: 'dashboard',
    path: '/suite',
    title: 'Career Intelligence Hub',
    subtitle: 'Every tool, plan, and signal in one workspace.',
    eyebrow: 'Workspace',
    icon: 'dashboard',
    group: 'Home',
    layoutVariant: 'standard',
    mobilePriority: 'quick',
    mobileEntry: 'route',
    mobileLabel: 'Home',
    mobileDescription: 'Today, plan status, usage, and workspace momentum.',
    mobileActionLabel: 'Open home',
  },
  {
    id: 'agent',
    path: '/suite/agent',
    title: 'Ask Taco',
    subtitle: 'Career context, next actions, and workflow help in one conversation.',
    eyebrow: 'Career agent',
    icon: 'auto_awesome',
    group: 'Taco',
    layoutVariant: 'agent',
    pageHelpId: 'agent',
    mobilePriority: 'quick',
    mobileEntry: 'focused',
    mobileLabel: 'Ask Taco',
    mobileDescription: 'Get the next best career action with saved context.',
    mobileActionLabel: 'Ask now',
  },
  {
    id: 'resume',
    path: '/suite/resume',
    title: 'Resume Studio',
    subtitle: 'Build, morph, verify, and export resumes with truth locks on.',
    eyebrow: 'Build',
    icon: 'description',
    group: 'Build',
    layoutVariant: 'editor',
    pageHelpId: 'resume',
    mobilePriority: 'quick',
    mobileEntry: 'focused',
    mobileHref: '/suite/resume?mobileAction=check',
    mobileLabel: 'Resume Check',
    mobileDescription: 'Run a fast resume review, then open full editing if needed.',
    mobileActionLabel: 'Check resume',
  },
  {
    id: 'ats-analyzer',
    path: '/suite/ats-analyzer',
    title: 'ATS Analyzer',
    subtitle: 'Preview how systems parse your resume and score job-specific keyword fit.',
    eyebrow: 'Build',
    icon: 'scanner',
    group: 'Build',
    layoutVariant: 'standard',
    pageHelpId: 'ats-analyzer',
    mobilePriority: 'quick',
    mobileEntry: 'focused',
    mobileHref: '/suite/ats-analyzer?mobileTab=score',
    mobileLabel: 'ATS Score',
    mobileDescription: 'Check parse quality and role keyword fit.',
    mobileActionLabel: 'Score resume',
  },
  {
    id: 'gallery',
    path: '/suite/gallery',
    title: 'Writing Toolkit',
    subtitle: 'Cover letters, LinkedIn, recruiter replies, humanizing, and message polish.',
    eyebrow: 'Build',
    icon: 'widgets',
    group: 'Build',
    layoutVariant: 'standard',
    pageHelpId: 'gallery',
    mobilePriority: 'quick',
    mobileEntry: 'focused',
    mobileHref: '/suite/writing-tools',
    mobileLabel: 'Humanize',
    mobileDescription: 'Polish career writing quickly from your phone.',
    mobileActionLabel: 'Humanize text',
  },
  {
    id: 'job-search',
    path: '/suite/job-search',
    title: 'Job Search Workbench',
    subtitle: 'Rank better roles, prepare packets, and keep jobs tied to your resume workflow.',
    eyebrow: 'Search and apply',
    icon: 'radar',
    group: 'Search and Apply',
    layoutVariant: 'workbench',
    pageHelpId: 'job-search',
    mobilePriority: 'standard',
    mobileEntry: 'route',
    mobileLabel: 'Job Search',
    mobileDescription: 'Review saved searches and recommended roles.',
    mobileActionLabel: 'Open jobs',
  },
  {
    id: 'market-oracle',
    path: '/suite/market-oracle',
    title: 'Market Oracle',
    subtitle: 'Decode role fit, market signals, salary context, and skill gaps before applying.',
    eyebrow: 'Search and apply',
    icon: 'troubleshoot',
    group: 'Search and Apply',
    layoutVariant: 'standard',
    pageHelpId: 'market-oracle',
    mobilePriority: 'desktopEnhanced',
    mobileEntry: 'focused',
    mobileLabel: 'Market Oracle',
    mobileDescription: 'Paste a JD for a decision summary; full analysis is best on larger screens.',
    mobileActionLabel: 'Open Oracle',
  },
  {
    id: 'applications',
    path: '/suite/applications',
    title: 'Applications Command Center',
    subtitle: 'Track the pipeline, spot what needs action, and keep follow-ups moving.',
    eyebrow: 'Search and apply',
    icon: 'work',
    group: 'Search and Apply',
    layoutVariant: 'workbench',
    pageHelpId: 'applications',
    mobilePriority: 'quick',
    mobileEntry: 'focused',
    mobileHref: '/suite/applications?mobileView=followups',
    mobileLabel: 'Follow-ups',
    mobileDescription: 'Check offers, interviews, follow-ups, and drafts due.',
    mobileActionLabel: 'Open pipeline',
  },
  {
    id: 'network',
    path: '/suite/network',
    title: 'Network CRM Command Center',
    subtitle: 'Track the people behind each opportunity and write the next message with context.',
    eyebrow: 'Search and apply',
    icon: 'contacts',
    group: 'Search and Apply',
    layoutVariant: 'workbench',
    pageHelpId: 'network',
    mobilePriority: 'standard',
    mobileEntry: 'route',
    mobileLabel: 'Network CRM',
    mobileDescription: 'Track contacts and relationship follow-ups.',
    mobileActionLabel: 'Open CRM',
  },
  {
    id: 'agent-queue',
    path: '/suite/agent/queue',
    title: 'Agent Queue',
    subtitle: 'Review AI-prepared application packets before they move forward.',
    eyebrow: 'Search and apply',
    icon: 'smart_toy',
    group: 'Search and Apply',
    layoutVariant: 'workbench',
    pageHelpId: 'agent-queue',
    mobilePriority: 'advanced',
    mobileEntry: 'route',
    mobileLabel: 'Agent Queue',
    mobileDescription: 'Review prepared application packets from Taco.',
    mobileActionLabel: 'Open queue',
  },
  {
    id: 'interview-sim',
    path: '/suite/interview-sim',
    title: 'Interview Studio',
    subtitle: 'Practice, whiteboard, and debrief with Taco-powered coaching.',
    eyebrow: 'Prepare',
    icon: 'interpreter_mode',
    group: 'Prepare',
    layoutVariant: 'workbench',
    pageHelpId: 'interview-sim',
    mobilePriority: 'quick',
    mobileEntry: 'focused',
    mobileHref: '/suite/interview-sim?mode=quick_drill',
    mobileLabel: 'Interview Prep',
    mobileDescription: 'Start a quick drill or prep session.',
    mobileActionLabel: 'Practice',
  },
  {
    id: 'stories',
    path: '/suite/agent/stories',
    title: 'Story Bank',
    subtitle: 'Capture truthful STAR stories and match them to hard interview questions.',
    eyebrow: 'Prepare',
    icon: 'auto_stories',
    group: 'Prepare',
    layoutVariant: 'workbench',
    pageHelpId: 'stories',
    mobilePriority: 'standard',
    mobileEntry: 'route',
    mobileLabel: 'Story Bank',
    mobileDescription: 'Review and reuse STAR stories.',
    mobileActionLabel: 'Open stories',
  },
  {
    id: 'skill-bridge',
    path: '/suite/skill-bridge',
    title: 'Skill Bridge',
    subtitle: 'Close skill gaps, prove readiness, and prepare before interviews.',
    eyebrow: 'Prepare',
    icon: 'route',
    group: 'Prepare',
    layoutVariant: 'workbench',
    pageHelpId: 'skill-bridge',
    mobilePriority: 'standard',
    mobileEntry: 'route',
    mobileLabel: 'Skill Bridge',
    mobileDescription: 'Check next skill gaps and proof work.',
    mobileActionLabel: 'Open gaps',
  },
  {
    id: 'intelligence',
    path: '/suite/intelligence',
    title: 'Career Intelligence',
    subtitle: 'Every tool connected, every signal counted.',
    eyebrow: 'Grow',
    icon: 'neurology',
    group: 'Grow',
    layoutVariant: 'standard',
    pageHelpId: 'intelligence',
    mobilePriority: 'standard',
    mobileEntry: 'route',
    mobileLabel: 'Intelligence',
    mobileDescription: 'Review career health and signals.',
    mobileActionLabel: 'Open insights',
  },
] as const satisfies readonly SuiteToolDefinition[];

export type SuiteToolId = (typeof suiteToolRegistry)[number]['id'];

export function getSuiteToolDefinition(idOrPath: string): SuiteToolDefinition | undefined {
  return suiteToolRegistry.find(tool => tool.id === idOrPath || tool.path === idOrPath);
}
