import { NextResponse, NextRequest } from 'next/server';
import { getAdminDb } from '@/lib/firebase-admin';
import { guardApiRoute } from '@/lib/api-auth';
import { validateBody } from '@/lib/validate';
import { VaultExportPlanSchema } from '@/lib/schemas';

export async function POST(req: NextRequest) {
  try {
    const guard = await guardApiRoute(req, { rateLimit: 5 });
    if (guard.error) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const validated = await validateBody(req, VaultExportPlanSchema);
    if (!validated.success) return validated.error;
    const { skill, schedule, summary: aiSummary, applicationId } = validated.data;

    let markdown = `# 🌉 Skill Bridge: ${skill} Training Curriculum\n\n`;
    if (aiSummary) markdown += `*${aiSummary}*\n\n`;
    
    if (applicationId) {
      markdown += `> 📌 **Context:** This curriculum was generated to bridge skill gaps for a specific Job Application. Keep track of your progress here!\n\n`;
    }

    markdown += `---\n\n`;

    schedule.forEach((day: any) => {
      markdown += `## Day ${day.day}: ${day.focus}\n`;
      markdown += `**⏱️ Time Estimate:** ${day.timeEstimate || '1.5h'}\n\n`;
      
      if (day.tasks && day.tasks.length > 0) {
        markdown += `### 🎯 Action Items\n`;
        day.tasks.forEach((task: string) => {
          markdown += `- [ ] ${task}\n`;
        });
        markdown += `\n`;
      }

      if (day.resources && day.resources.length > 0) {
        markdown += `### 📚 Required Resources\n`;
        day.resources.forEach((res: any) => {
          const typeIcon = res.type === 'video' ? '📺' : res.type === 'article' ? '📰' : '📘';
          markdown += `- ${typeIcon} [${res.title}](${res.url})\n`;
        });
        markdown += `\n`;
      }
      
      markdown += `---\n\n`;
    });

    markdown += `\n*Note: This material was auto-generated by the Talent Consulting Study Engine.*`;

    // Save to Firestore 'study_vault'
    const vaultItem = {
      userId: guard.user?.uid || 'anonymous',
      type: 'skill-bridge', 
      topic: `${skill} Syllabus`,
      summary: markdown,
      applicationId: applicationId || null,
      createdAt: new Date().toISOString(),
    };

    const docRef = await getAdminDb().collection('study_vault').add(vaultItem);

    return NextResponse.json({ success: true, id: docRef.id });

  } catch (error: unknown) {
    console.error('[api/vault/export-plan] Error:', error);
    return NextResponse.json({ error: 'Failed to export to Vault' }, { status: 500 });
  }
}
